### ISSUE TITLE
Add support for salt master file server

### ISSUE THREAD

**Issue by grandmasterv** [myuen/salt#2]
The file locations for your software binaries and sources need to updated to add a reference for the salt master in addition to a local directory.  Referencing the local directory works as you are developing these states using a masterless minion but this won't work from a master.  Thankfully we can put both a local source AND a salt master file server source in the states.  Salt will look for the file in each one starting at the top and stop once it finds the file in a location.

We are placing all of our linux software for installation in the following path on the master.  
`salt://linux`
Steve and I discussed the further sub folders of binaries and sources you have and like the idea.  We will also be adding another sub folder called scripts.
`salt://linux/binaries`
`salt://linux/sources`
`salt://linux/scripts`

Here is an example of how to add a reference to this location from your states:
```
- source: '/srv/salt/install/binaries/BBMap_37.36.tar.gz'
```
becomes
```
- source: 'salt://linux/binaries/BBMap_37.36.tar.gz'
- source: '/srv/salt/install/binaries/BBMap_37.36.tar.gz'
```

I will also of course need the contents of your `/srv/salt/install` folder along with these states to be able to deploy the software.

Further reading:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed

**Comment by myuen** [comment]
Added salt master file server as new source location.
